WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 620
FACTOR = 1
VIRTUAL_WIDTH = WINDOW_WIDTH*FACTOR
VIRTUAL_HEIGHT = WINDOW_HEIGHT*FACTOR
CUSTOM_WIDTH = 0
CUSTOM_HEIGHT = 0
flag = 0 
TITLE = 'Flappy Bird!'
BACKGROUND_IMG = 'background.png'
BACKGROUND_IMG_LOOPING_POINT = 792+WINDOW_WIDTH --do not change this value
GROUND_IMG_LOOPING_POINT = 110	 --do not change this value
GROUND_IMG = 'ground.png'
npipes = {}
SCORE = 0
backgroundScroll = 0
backgroundScrollSpeed = 100
groundScroll = 0
groundScrollSpeed = 200
game_state = 0
HIT_SOUND = "Hit.wav"
JUMP_SOUND = "Jump.wav"